[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#FF007A"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1C1D24"
textColor = "#FFFFFF"
font = "sans serif"
